import { createFileRoute } from "@tanstack/react-router";
import { PageHeader, Panel } from "@/components/panel";
import { RiskBadge } from "@/components/risk-badge";
import { countryHeat, emergingThreats, fraudTrend, kpis } from "@/lib/mock-data";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertOctagon, Brain, Eye, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";

export const Route = createFileRoute("/command")({
  head: () => ({ meta: [{ title: "Fraud Command Center — AFIOS" }] }),
  component: CommandCenterPage,
});

function CommandCenterPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Executive · Single Pane of Glass"
        title="Fraud Command Center"
        description="Mission control for fraud operations. Live posture, AI insights, and operational throughput — built for executives and fraud managers."
        action={<div className="surface-panel inline-flex items-center gap-2 h-9 px-3 text-[12px]"><span className="h-2 w-2 rounded-full bg-status-clear pulse-critical" /><span className="mono uppercase tracking-wider text-muted-foreground">All systems · Nominal</span></div>}
      />

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        {[
          { i: ShieldCheck, l: "Loss prevented", v: "$12.4M", d: "+18.4%", tone: "good" },
          { i: AlertOctagon, l: "Fraud rate", v: "0.074%", d: "-1.2 bps", tone: "good" },
          { i: TrendingUp, l: "Detection rate", v: "94.6%", d: "+0.3%", tone: "good" },
          { i: Eye, l: "False positive", v: "2.1%", d: "-0.4%", tone: "good" },
          { i: AlertOctagon, l: "Active threats", v: "11", d: "3 critical", tone: "warn" },
          { i: Brain, l: "Open investigations", v: "412", d: "+11", tone: "neutral" },
        ].map((k, i) => (
          <div key={i} className="surface-panel p-4">
            <div className="flex items-center justify-between"><k.i className="h-4 w-4 text-primary" />
              <span className={`text-[11px] mono tabular ${k.tone === "good" ? "text-status-clear" : k.tone === "warn" ? "text-risk-high" : "text-muted-foreground"}`}>{k.d}</span>
            </div>
            <div className="mt-2 text-2xl font-semibold tabular">{k.v}</div>
            <div className="text-[10px] mono uppercase tracking-widest text-muted-foreground mt-0.5">{k.l}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Panel className="lg:col-span-2" title="AI insight — emerging campaigns" subtitle="Generated by Threat Intelligence Copilot · last 6h">
          <ul className="space-y-3">
            {[
              { sev: "critical", t: "Synthetic ID ring expanding into MX retail banking", d: "287 new applications matching cluster #88 fingerprint in last 24h. Recommend tightening velocity rule R-441 across LATAM corridor." },
              { sev: "high", t: "Card-testing burst targeting tier-1 eCommerce", d: "BIN range 4147** showing 14x normal authorization volume. Auto-mitigation engaged at 04:12 UTC." },
              { sev: "medium", t: "Wallet drainer phishing kit v3 distribution increasing", d: "Cluster of 41 newly funded wallets matched against threat feed. Watch-listed for outbound monitoring." },
            ].map((t, i) => (
              <li key={i} className="surface-panel p-3 flex items-start gap-3">
                <Sparkles className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                <div className="flex-1">
                  <div className="flex items-center gap-2"><RiskBadge level={t.sev as any} /><span className="font-medium text-[13.5px]">{t.t}</span></div>
                  <div className="text-[12.5px] text-muted-foreground mt-1">{t.d}</div>
                </div>
                <button className="h-7 px-2.5 surface-panel text-[11px] mono uppercase tracking-wider shrink-0">Investigate</button>
              </li>
            ))}
          </ul>
        </Panel>

        <Panel title="Risk forecast" subtitle="Next 7 days · ARIMA + GBM">
          <div className="h-[200px]">
            <ResponsiveContainer>
              <AreaChart data={fraudTrend.slice(-14)} margin={{ top: 8, right: 8, left: -16, bottom: 0 }}>
                <defs><linearGradient id="cmd-g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.5} /><stop offset="100%" stopColor="var(--primary)" stopOpacity={0} /></linearGradient></defs>
                <CartesianGrid stroke="var(--border)" strokeDasharray="2 4" vertical={false} />
                <XAxis dataKey="day" tick={{ fill: "var(--muted-foreground)", fontSize: 9, fontFamily: "var(--font-mono)" }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: "var(--muted-foreground)", fontSize: 9, fontFamily: "var(--font-mono)" }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={{ background: "var(--surface)", border: "1px solid var(--border)", fontSize: 11 }} />
                <Area type="monotone" dataKey="fraud" stroke="var(--primary)" strokeWidth={1.5} fill="url(#cmd-g)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
          <div className="mt-3 text-[12.5px] surface-panel p-3 bg-primary/5 border-primary/30">
            <div className="text-[10px] mono uppercase tracking-widest text-primary mb-1">Forecast</div>
            Fraud volume expected to rise <span className="text-foreground font-medium">+24%</span> over next 7 days driven by holiday eCommerce traffic.
          </div>
        </Panel>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Panel title="Global fraud map" subtitle="Live signal density" className="lg:col-span-2">
          <div className="grid grid-cols-6 sm:grid-cols-12 gap-1.5">
            {countryHeat.map(c => {
              const intensity = Math.min(1, c.v / 8500);
              return (
                <div key={c.c} className="aspect-square rounded grid place-items-center text-[10px] mono"
                  style={{
                    background: `color-mix(in oklch, var(--risk-critical) ${Math.round(intensity * 80)}%, var(--surface-2))`,
                    color: intensity > 0.5 ? "white" : "var(--muted-foreground)",
                  }}>{c.c}</div>
              );
            })}
          </div>
        </Panel>

        <Panel title="Operational metrics" subtitle="Today">
          <ul className="space-y-3 text-[12.5px]">
            {[
              { l: "Alert volume", v: "1,284", b: 72 },
              { l: "Investigation backlog", v: "318", b: 41 },
              { l: "Analyst productivity", v: "87%", b: 87 },
              { l: "SLA compliance", v: "96.4%", b: 96 },
            ].map(r => (
              <li key={r.l}>
                <div className="flex justify-between"><span className="text-muted-foreground">{r.l}</span><span className="mono tabular">{r.v}</span></div>
                <div className="mt-1.5 h-1.5 bg-surface-3 rounded-full overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-primary to-chart-2 rounded-full" style={{ width: `${r.b}%` }} />
                </div>
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <Panel title="Threat intelligence feed" subtitle="Live · cross-institution + open-source">
        <ul className="divide-y divide-border -m-4">
          {emergingThreats.map(t => (
            <li key={t.id} className="px-4 py-3 hover:bg-surface-2/40 flex items-center gap-3">
              <RiskBadge level={t.severity as any} />
              <div className="flex-1 min-w-0">
                <div className="text-[13px] font-medium truncate">{t.name}</div>
                <div className="text-[11px] mono text-muted-foreground">{t.id} · {t.region} · velocity +{t.delta}%</div>
              </div>
              <button className="h-7 px-2.5 surface-panel text-[11px] mono uppercase tracking-wider">Subscribe</button>
            </li>
          ))}
        </ul>
      </Panel>
    </div>
  );
}
