/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommandRouteImport } from './routes/command'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/command': typeof CommandRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/dna': typeof DnaRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/feedback': typeof FeedbackRoute
  '/forecasting': typeof ForecastingRoute
  '/governance': typeof GovernanceRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/risk': typeof RiskRoute
  '/simulation': typeof SimulationRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/command': typeof CommandRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/dna': typeof DnaRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/feedback': typeof FeedbackRoute
  '/forecasting': typeof ForecastingRoute
  '/governance': typeof GovernanceRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/risk': typeof RiskRoute
  '/simulation': typeof SimulationRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/command': typeof CommandRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/dna': typeof DnaRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/feedback': typeof FeedbackRoute
  '/forecasting': typeof ForecastingRoute
  '/governance': typeof GovernanceRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/risk': typeof RiskRoute
  '/simulation': typeof SimulationRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/command'
    | '/compliance'
    | '/copilot'
    | '/dna'
    | '/enterprise'
    | '/features'
    | '/feedback'
    | '/forecasting'
    | '/governance'
    | '/graph'
    | '/investigations'
    | '/memory'
    | '/models'
    | '/monitoring'
    | '/risk'
    | '/simulation'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/command'
    | '/compliance'
    | '/copilot'
    | '/dna'
    | '/enterprise'
    | '/features'
    | '/feedback'
    | '/forecasting'
    | '/governance'
    | '/graph'
    | '/investigations'
    | '/memory'
    | '/models'
    | '/monitoring'
    | '/risk'
    | '/simulation'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/command'
    | '/compliance'
    | '/copilot'
    | '/dna'
    | '/enterprise'
    | '/features'
    | '/feedback'
    | '/forecasting'
    | '/governance'
    | '/graph'
    | '/investigations'
    | '/memory'
    | '/models'
    | '/monitoring'
    | '/risk'
    | '/simulation'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  CommandRoute: typeof CommandRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  DnaRoute: typeof DnaRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FeaturesRoute: typeof FeaturesRoute
  FeedbackRoute: typeof FeedbackRoute
  ForecastingRoute: typeof ForecastingRoute
  GovernanceRoute: typeof GovernanceRoute
  GraphRoute: typeof GraphRoute
  InvestigationsRoute: typeof InvestigationsRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  MonitoringRoute: typeof MonitoringRoute
  RiskRoute: typeof RiskRoute
  SimulationRoute: typeof SimulationRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  CommandRoute: CommandRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  DnaRoute: DnaRoute,
  EnterpriseRoute: EnterpriseRoute,
  FeaturesRoute: FeaturesRoute,
  FeedbackRoute: FeedbackRoute,
  ForecastingRoute: ForecastingRoute,
  GovernanceRoute: GovernanceRoute,
  GraphRoute: GraphRoute,
  InvestigationsRoute: InvestigationsRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  MonitoringRoute: MonitoringRoute,
  RiskRoute: RiskRoute,
  SimulationRoute: SimulationRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
